---
version: "2"
plugins:
  brakeman:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 55
