# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4dc7efaad79f705976c2cb2f8738b7f41c9b6470c2408b1892823b3b6887103a940228110e96231d30579991fb2e496e0fa15c72eaac12b6edc210d083687dc

test:
  secret_key_base: ffe5f04b06183e880e546d6a0042cdaf199df10134a1d88cca27d6d9ac1a73ab0f946285ac11ba2e31b180e6f4673497ec9e8a2f9954704eaf402f5243fc359f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
